-- Additional seed data for notifications
INSERT INTO notifications (notification_id, message, url, created_at, updated_at) VALUES
(1, 'Welcome back! Check out what’s new on LearnHub.', 'http://learnhub.local', NOW(), NOW()),
(2, 'Your feedback matters! Take our quick survey.', 'http://learnhub.local', NOW(), NOW()),
(3, 'New blog post: Tips for effective online learning.', 'http://learnhub.local', NOW(), NOW()),
(4, 'Invite your friends to LearnHub and earn rewards.', 'http://learnhub.local', NOW(), NOW()),
(5, 'We’ve updated our Terms of Service. Please review.', 'http://learnhub.local', NOW(), NOW()),
(6, 'Congratulations on completing your first course!', 'http://learnhub.local', NOW(), NOW()),
(7, 'LearnHub is now available on mobile! Download the app.', 'http://learnhub.local', NOW(), NOW()),
(8, 'Join our live webinar this Friday at 5 PM.', 'http://learnhub.local', NOW(), NOW()),
(9, 'Your subscription is about to expire. Renew now.', 'http://learnhub.local', NOW(), NOW()),
(10, 'Discover trending courses on LearnHub today.', 'http://learnhub.local', NOW(), NOW()),
(11, 'Explore new features added to your dashboard.', 'http://learnhub.local', NOW(), NOW()),
(12, 'Check out our latest course recommendations.', 'http://learnhub.local', NOW(), NOW()),
(13, 'LearnHub now supports multiple languages!', 'http://learnhub.local', NOW(), NOW()),
(14, 'Your progress report is ready. View it now.', 'http://learnhub.local', NOW(), NOW()),
(15, 'Join our community forum and connect with peers.', 'http://learnhub.local', NOW(), NOW());

-- Additional seed data for notification_users
INSERT INTO notification_users (notification_user_id, notification_id, user_id, is_read) VALUES
(1, 1, 1, 1),
(2, 1, 2, 0),
(3, 2, 1, 0),
(4, 2, 2, 1),
(5, 3, 1, 0),
(6, 3, 2, 0),
(7, 4, 1, 1),
(8, 4, 2, 0),
(9, 5, 1, 0),
(10, 5, 2, 1),
(11, 6, 1, 0),
(12, 6, 2, 0),
(13, 7, 1, 0),
(14, 7, 2, 1),
(15, 8, 1, 0),
(16, 8, 2, 0),
(17, 9, 1, 1),
(18, 9, 2, 0),
(19, 10, 1, 0),
(20, 10, 2, 0),
(21, 11, 1, 1),
(22, 11, 2, 0),
(23, 12, 1, 0),
(24, 12, 2, 0),
(25, 13, 1, 0),
(26, 13, 2, 1),
(27, 14, 1, 0),
(28, 14, 2, 0),
(29, 15, 1, 1),
(30, 15, 2, 0);