INSERT INTO course_modules (module_id, course_id, title, description) VALUES
(1, 1, 'Introduction to Programming', 'Basic concepts of programming including variables, loops, and functions'),
(2, 1, 'Control Structures', 'Understanding if-else statements, switch cases, and loops in detail'),
(3, 2, 'HTML Basics', 'Introduction to HTML tags and document structure'),
(4, 2, 'CSS Fundamentals', 'Learning CSS selectors, properties, and styling techniques'),
(5, 3, 'Database Design', 'Understanding database schemas and relationships'),
(6, 3, 'SQL Queries', 'Writing basic to advanced SQL queries'),
(7, 4, 'Python Syntax', 'Introduction to Python programming language basics'),
(8, 4, 'Python Functions', 'Understanding functions, parameters, and return values'),
(9, 5, 'JavaScript Fundamentals', 'Basic concepts of JavaScript programming'),
(10, 5, 'DOM Manipulation', 'Working with Document Object Model in JavaScript'),
(11, 6, 'React Components', 'Understanding React component architecture'),
(12, 6, 'State Management', 'Managing state in React applications'),
(13, 7, 'Network Basics', 'Introduction to computer networking concepts'),
(14, 7, 'Protocols', 'Understanding different networking protocols'),
(15, 8, 'Data Structures', 'Basic data structures implementation'),
(16, 8, 'Algorithms', 'Common algorithmic problems and solutions'),
(17, 9, 'Cloud Computing Basics', 'Introduction to cloud services and deployment'),
(18, 9, 'AWS Services', 'Overview of main AWS services'),
(19, 10, 'Mobile App Design', 'Principles of mobile application design'),
(20, 10, 'App Development', 'Building mobile applications using modern frameworks');
