<?php

declare(strict_types=1);

namespace App\Services;

use App\Config\AppConstants;
use Framework\Database;
use TCPDF;

class ReportService
{
    public  function __construct(private Database $db) {}

    public function generateReportForTeacher(string $startDate, string $endDate, string $tutorId)

    {
        $reportData = $this->createTeacherReportData($tutorId, $startDate, $endDate);
        $teacherName = $reportData['teacher_name'];
        $startDate = $reportData['start_date'];
        $endDate = $reportData['end_date'];
        $onetime_courses = $reportData['onetime_courses'];
        $recurring_courses = $reportData['recurring_courses'];
        $onetime_total = $reportData['onetime_total'];
        $recurring_total = $reportData['recurring_total'];
        $grand_total = $reportData['grand_total'];

        // Create new PDF document
        $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

        // Set document information
        $pdf->SetCreator('LearnHub');
        $pdf->SetAuthor('LearnHub System');
        $pdf->SetTitle('Teacher Report');
        $pdf->SetSubject('Report for Teacher');
        $pdf->SetKeywords('report, teacher, pdf');

        // Set default header data
        $pdf->SetHeaderData('', 0, '', "Generated by LearnHub");

        // Set header and footer fonts
        $pdf->setHeaderFont(['helvetica', '', 12]);
        $pdf->setFooterFont(['helvetica', '', 10]);

        // Set default monospaced font
        $pdf->SetDefaultMonospacedFont('courier');

        // Set margins
        $pdf->SetMargins(15, 27, 15);
        $pdf->SetHeaderMargin(5);
        $pdf->SetFooterMargin(10);

        // Set auto page breaks
        $pdf->SetAutoPageBreak(TRUE, 25);

        // Add a page
        $pdf->AddPage();

        // Set font styles
        $pdf->SetFont('helvetica', '', 12);

        // CSS styling for the report (only inside <style> tag)
        $style = '<style>
            body {
                font-family: helvetica, sans-serif;
            }
            h1 {
                color: #222;
                font-size: 22pt;
                text-align: center;
                margin-bottom: 15px;
                padding-bottom: 10px;
            }
            h2 {
                color: #444;
                font-size: 16pt;
                margin-top: 20px;
                margin-bottom: 10px;
            }
            .teacher-info .label {
                font-weight: bold;
                color: #333;
                display: inline-block;
            }
            .teacher-info .period {
                display: block;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 15px;
                box-shadow: 0 1px 3px rgba(0,0,0,0.07);
                table-layout: fixed;
            }
            th {
                background-color: #f5f5f5;
                color: #222;
                font-weight: bold;
                text-align: center;
                padding: 10px;
                border: 1px solid #e0e0e0;
                overflow: hidden;
            }
            td {
                text-align: left;
                padding: 8px 10px;
                border: 1px solid #e9ecef;
                vertical-align: middle;
                overflow: hidden;
            }
            td.center {
                text-align: center;
            }
            tr:nth-child(even) {
                background-color: #fcfcfc;
            }
            tr:hover {
                background-color: #f0f4fa;
            }
            .total-row {
                background-color: #ffeeba;
                color: #222;
                font-weight: bold;
                border-top: 2px solid #ffc400;
            }
            .amount {
                text-align: right;
                font-family: "Courier New", Courier, monospace;
            }
            .report-footer {
                margin-top: 20px;
                font-size: 9pt;
                color: #888;
                text-align: center;
            }
            .timestamp {
                font-style: italic;
                margin-top: 5px;
            }
            .text-right {
                text-align: right;
            }
            .colspan-2 {
                column-span: 2;
            }
            .grand-total-table {
                margin-top: 40px;
                border-top: 3px solid #ffc400;
                padding-top: 10px;
            }
            .spacer {
                height: 50px;
                clear: both;
            }
        </style>';

        // Build HTML content for the teacher report
        $html = $style;
        $html .= "<h1>Teacher Report</h1>";
        $html .= "<div class=\"teacher-info\">
                    <div><span class=\"label\">Teacher Name:</span> {$teacherName}</div>
                    <div class=\"period\"><span class=\"label\">Period:</span> {$startDate} to {$endDate}</div>
                  </div>";

        // One-time courses table
        $html .= "<h2>One-time Courses</h2>";
        $html .= "<table cellpadding=\"6\">
            <thead>
            <tr>
                <th>Course</th>
                <th>Number of Students</th>
                <th>Payments Received</th>
            </tr>
            </thead>
            <tbody>";
        foreach ($onetime_courses as $course) {
            $html .= "<tr>
            <td>{$course['title']}</td>
            <td class=\"center\">{$course['students']}</td>
            <td class=\"amount\">Rs." . number_format((float)$course['payments'], 2) . "</td>
              </tr>";
        }
        $html .= "<tr class=\"total-row\">
            <td colspan=\"2\" class=\"text-right\"><strong>Total Payments:</strong></td>
            <td class=\"amount\"><strong>Rs." . number_format($onetime_total, 2) . "</strong></td>
              </tr>";
        $html .= "</tbody></table>";

        // Recurring courses table
        $html .= "<h2>Recurring Courses</h2>";
        $html .= "<table cellpadding=\"6\">
            <thead>
            <tr>
                <th>Course</th>
                <th>Number of Students</th>
                <th>Payments Received</th>
            </tr>
            </thead>
            <tbody>";
        foreach ($recurring_courses as $course) {
            $html .= "<tr>
            <td>{$course['title']}</td>
            <td class=\"center\">{$course['students']}</td>
            <td class=\"amount\">Rs." . number_format((float)$course['payments'], 2) . "</td>
              </tr>";
        }
        $html .= "<tr class=\"total-row\">
            <td colspan=\"2\" class=\"text-right\"><strong>Total Payments:</strong></td>
            <td class=\"amount\"><strong>Rs." . number_format($recurring_total, 2) . "</strong></td>
              </tr>";
        $html .= "</tbody></table>";

        // Add spacer
        $html .= "<div class=\"spacer\"></div>";

        // Grand total row
        $html .= "<table cellpadding=\"6\" class=\"grand-total-table\">
            <tr class=\"total-row\">
                <td colspan=\"2\" class=\"text-right\"><strong>Grand Total:</strong></td>
                <td class=\"amount\"><strong>Rs." . number_format($grand_total, 2) . "</strong></td>
            </tr>
        </table>";

        // Add timestamp and additional footer information
        $currentDate = date('F j, Y, g:i a');
        $html .= "<div class='report-footer'>
            <div class='timestamp'>Generated on: {$currentDate}</div>
        </div>";

        // Output the HTML content
        $pdf->writeHTML($html, true, false, true, false, '');

        // Output PDF to browser (for download)
        $pdf->Output('teacher_report.pdf', 'I');
    }

    public function getTotalPaymentsForOneTimeCourses(string $tutorId, string $startDate, string $endDate)
    {
        $result = $this->db->query(
            "SELECT c.course_id, c.title, SUM(p.amount) as total_payments 
            FROM payments p INNER JOIN course_payments cp ON p.payment_id = cp.payment_id INNER JOIN courses c ON cp.course_id = c.course_id 
            WHERE c.tutor_id = :tutorId
            AND p.payment_status = :payment_status
            AND p.updated_date BETWEEN :startDate AND :endDate
            AND c.billing_type = :billing_type
                GROUP BY course_id",
            [
                'tutorId' => $tutorId,
                'startDate' => $startDate,
                'endDate' => $endDate,
                'billing_type' => 'onetime',
                'payment_status' => AppConstants::PAYMENT_STATUS_SUCCESS
            ]
        );

        return $result->findAll();
    }

    private function getTotalPaymentsForReccuringCourses(string $tutorId, string $startDate, string $endDate)
    {
        $result = $this->db->query(
            "SELECT c.course_id, c.title, SUM(p.amount) as total_payments 
            FROM payments p INNER JOIN course_payments cp ON p.payment_id = cp.payment_id INNER JOIN courses c ON cp.course_id = c.course_id 
            WHERE c.tutor_id = :tutorId
            AND p.payment_status = :payment_status
            AND p.updated_date BETWEEN :startDate AND :endDate
            AND c.billing_type = :billing_type
                GROUP BY course_id",
            [
                'tutorId' => $tutorId,
                'startDate' => $startDate,
                'endDate' => $endDate,
                'billing_type' => 'recurring',
                'payment_status' => AppConstants::PAYMENT_STATUS_SUCCESS
            ]
        );

        return $result->findAll();
    }

    private function getNumberOfStudentsEnrolledForOneTimeCourses(string $tutorId, string $startDate, string $endDate)
    {
        $result = $this->db->query(
            "SELECT c.course_id, c.title, COUNT(DISTINCT cp.user_id) as enrolled_students
            FROM courses c
            LEFT JOIN course_payments cp ON c.course_id = cp.course_id
            LEFT JOIN payments p ON cp.payment_id = p.payment_id
            WHERE c.tutor_id = :tutorId
            AND c.billing_type = :billing_type
            AND p.payment_status = :payment_status
            AND p.updated_date BETWEEN :startDate AND :endDate
            AND (
                SELECT SUM(p2.amount) 
                FROM payments p2 
                JOIN course_payments cp2 ON p2.payment_id = cp2.payment_id 
                WHERE cp2.user_id = cp.user_id 
                AND cp2.course_id = c.course_id 
                AND p2.payment_status = :payment_status
            ) >= c.price
            GROUP BY c.course_id, c.title",
            [
                'tutorId' => $tutorId,
                'startDate' => $startDate,
                'endDate' => $endDate,
                'billing_type' => 'onetime',
                'payment_status' => AppConstants::PAYMENT_STATUS_SUCCESS
            ]
        );

        return $result->findAll();
    }

    private function getNumberOfStudentsEnrolledForRecurringCourses(string $tutorId, string $startDate, string $endDate)
    {
        $result = $this->db->query(
            "SELECT c.course_id, c.title, COUNT(DISTINCT cp.user_id) as enrolled_students
                FROM courses c
                LEFT JOIN course_payments cp ON c.course_id = cp.course_id
                LEFT JOIN payments p ON cp.payment_id = p.payment_id
                LEFT JOIN recurring_course_sub_periods rcsp ON cp.sub_period_id = rcsp.sub_period_id AND cp.course_id = rcsp.course_id
                WHERE c.tutor_id = :tutorId
                AND c.billing_type = :billing_type
                AND p.payment_status = :payment_status
                AND p.updated_date BETWEEN :startDate AND :endDate
                AND (
                    SELECT SUM(p2.amount) 
                    FROM payments p2 
                    JOIN course_payments cp2 ON p2.payment_id = cp2.payment_id 
                    WHERE cp2.user_id = cp.user_id 
                    AND cp2.course_id = c.course_id
                    AND cp2.sub_period_id = cp.sub_period_id
                    AND p2.payment_status = :payment_status
                ) >= rcsp.price
                GROUP BY c.course_id, c.title",
            [
                'tutorId' => $tutorId,
                'startDate' => $startDate,
                'endDate' => $endDate,
                'billing_type' => 'recurring',
                'payment_status' => AppConstants::PAYMENT_STATUS_SUCCESS
            ]
        );
        return $result->findAll();
    }

    private function createTeacherReportData(string $tutorId, string $startDate, string $endDate)
    {
        $teacherName = (string) $this->db->query(
            "SELECT CONCAT(first_name, ' ', last_name) AS teacher_name FROM users WHERE user_id = :tutorId",
            ['tutorId' => $tutorId]
        )->find()['teacher_name'] ?? '';
        // Get one-time courses stats (payments and enrollments)
        $onetimePayments = $this->getTotalPaymentsForOneTimeCourses($tutorId, $startDate, $endDate);
        $onetimeEnrollments = $this->getNumberOfStudentsEnrolledForOneTimeCourses($tutorId, $startDate, $endDate);

        // Get recurring courses stats (payments and enrollments)
        $recurringPayments = $this->getTotalPaymentsForReccuringCourses($tutorId, $startDate, $endDate);
        $recurringEnrollments = $this->getNumberOfStudentsEnrolledForRecurringCourses($tutorId, $startDate, $endDate);

        // Combine data by course_id for one-time courses
        $onetimeCourseStats = [];
        foreach ($onetimeEnrollments as $enrollment) {
            $courseId = $enrollment['course_id'];
            $onetimeCourseStats[$courseId] = [
                'course_id' => $courseId,
                'title' => $enrollment['title'],
                'students' => $enrollment['enrolled_students'],
                'payments' => 0
            ];
        }

        foreach ($onetimePayments as $payment) {
            $courseId = $payment['course_id'];
            if (isset($onetimeCourseStats[$courseId])) {
                $onetimeCourseStats[$courseId]['payments'] = $payment['total_payments'];
            }
        }

        // Combine data by course_id for recurring courses
        $recurringCourseStats = [];
        foreach ($recurringEnrollments as $enrollment) {
            $courseId = $enrollment['course_id'];
            $recurringCourseStats[$courseId] = [
                'course_id' => $courseId,
                'title' => $enrollment['title'],
                'students' => $enrollment['enrolled_students'],
                'payments' => 0
            ];
        }

        foreach ($recurringPayments as $payment) {
            $courseId = $payment['course_id'];
            if (isset($recurringCourseStats[$courseId])) {
                $recurringCourseStats[$courseId]['payments'] = $payment['total_payments'];
            }
        }

        // Convert to indexed arrays
        $onetimeCourseStats = array_values($onetimeCourseStats);
        $recurringCourseStats = array_values($recurringCourseStats);

        // Calculate totals
        $onetimeTotal = 0;
        foreach ($onetimeCourseStats as $course) {
            $onetimeTotal += (float)$course['payments'];
        }

        $recurringTotal = 0;
        foreach ($recurringCourseStats as $course) {
            $recurringTotal += (float)$course['payments'];
        }

        // Calculate grand total
        $grandTotal = $onetimeTotal + $recurringTotal;
        $reportData = [
            'teacher_name' => $teacherName,
            'start_date' => $startDate,
            'end_date' => $endDate,
            'onetime_courses' => $onetimeCourseStats,
            'recurring_courses' => $recurringCourseStats,
            'onetime_total' => $onetimeTotal,
            'recurring_total' => $recurringTotal,
            'grand_total' => $grandTotal,
        ];
        return $reportData;
    }
}
